name: prestou
description: "A new Flutter project."
publish_to: 'br.com.prestou'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  flutter_masked_text2: ^0.9.1
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
